### ISSUE TITLE
Networking does not work on 2020 PC - r8169 unknown chip XID 54B

### ISSUE THREAD

**Issue by slrslr** [redorescue/redorescue#91]
Hello,
sorry to bother You. Like 2 month old RedoRescue 4:

![redorescue4_r8169_unknown_chip_xid_54b](https://user-images.githubusercontent.com/6596726/148946239-bb5314dd-3afb-41bb-a340-d5aea879ef2e.jpg)

And networking does not work.

I think that only newer kernel support these network chips (5.12+ ?).

Manajro report this network adapter like this:
```
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
    vendor: Hewlett-Packard driver: r8169 v: kernel port: 2200 bus-ID: 03:00.1
    chip-ID: 10ec:8168 class-ID: 0200

```
